server:
  port: 6003

spring:
  application:
    name: SERVICE-TEACHER

  datasource:
    url: jdbc:postgresql://localhost:5000/TeacherDb
    username: postgres
    password: alae_postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ou "create-drop" pour le d√©veloppement
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/university_realm
          jwk-set-uri: http://localhost:8181/realms/university_realm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Logging pour debug
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.example: DEBUG