server:
  port: 6002

spring:
  application:
    name: SERVICE-STUDENT

  data:
    mongodb:
      host: localhost
      port: 27017
      database: student_db

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/university_realm
          jwk-set-uri: http://localhost:8181/realms/university_realm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Add this for debugging
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.example: DEBUG