services:
  mysql:
    image: mysql:8.3.0
    container_name: SQL
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: schedule_service  # ✅ Changé
